pages:
    image: node:lts

    before_script:
        - corepack enable
        - pnpm install --frozen-lockfile

    script:
        - pnpm run build

    artifacts:
        paths:
            - public
    only:
        - master
