image: python:latest

# Functions that should be executed before the build script is run
pages:
  before_script:
    - ldd --version
    - echo deb http://ftp.debian.org/debian experimental main contrib non-free > /etc/apt/sources.list
    - apt-get update
    - apt-get install -y imagemagick ffmpeg libc6
    - pip install poetry
    - poetry config virtualenvs.in-project true
    - poetry install
  cache:
    paths:
      - .venv
      - ortfodb
      - projects
      - media
      - .lastbuild.yaml
  script:
    - mkdir public
    - chmod +x build.sh
    - ./build.sh
    - cp -rv media/ public/
    - cp -rv */*.html public/
    - cp -rv *.html public/
    - cp -rv *.pdf public/
    - cp -rv js public/
    - cp -rv css public/
    - cp -rv images public/
    - cp favicon.ico public/
    - cp .htaccess public/
    - cp robots.txt public/
    - cp *.pdf public/
    - cp _redirects public/
    - cp bureau.yaml public/
  artifacts:
    paths:
      # The folder that contains the files to be exposed at the Page URL
      - public
  rules:
    # This ensures that only pushes to the default branch will trigger
    # a pages deploy
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
