# The Docker image that will be used to build your app
image: alpine:latest
# Functions that should be executed before the build script is run
before_script: []
pages:
  script:
    - mkdir public
    - cp -rv */*.html public/
    - cp -rv *.html public/
    - cp -rv *.pdf public/
    - cp -rv js public/
    - cp -rv css public/
    - cp -rv images public/
    - cp -rv video public/
    - cp favicon.ico public/
    - cp .htaccess public/
    - cp robots.txt public/
    - cp *.pdf public/
    - cp _redirects public/
  artifacts:
    paths:
      # The folder that contains the files to be exposed at the Page URL
      - public
  rules:
    # This ensures that only pushes to the default branch will trigger
    # a pages deploy
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
